telephony/java/android/telephony/SmsManager.java
telephony/java/android/telephony/SmsMessage.java
telephony/java/android/telephony/cdma/package.html
telephony/java/android/telephony/gsm/SmsMessage.java
telephony/java/com/android/internal/telephony/CommandException.java
telephony/java/com/android/internal/telephony/DataConnection.java
telephony/java/com/android/internal/telephony/DataConnectionTracker.java
telephony/java/com/android/internal/telephony/DataLink.java
telephony/java/com/android/internal/telephony/DataLinkInterface.java
telephony/java/com/android/internal/telephony/EncodeException.java
telephony/java/com/android/internal/telephony/GsmAlphabet.java
telephony/java/com/android/internal/telephony/ISms.aidl
telephony/java/com/android/internal/telephony/SMSDispatcher.java
telephony/java/com/android/internal/telephony/SmsAddress.java
telephony/java/com/android/internal/telephony/SmsHeader.java
telephony/java/com/android/internal/telephony/SmsMessageBase.java
telephony/java/com/android/internal/telephony/SmsRawData.aidl
telephony/java/com/android/internal/telephony/SmsRawData.java
telephony/java/com/android/internal/telephony/SmsResponse.java
telephony/java/com/android/internal/telephony/cdma/CdmaDataConnection.java
telephony/java/com/android/internal/telephony/cdma/CdmaDataConnectionTracker.java
telephony/java/com/android/internal/telephony/cdma/CdmaSMSDispatcher.java
telephony/java/com/android/internal/telephony/cdma/FeatureCode.java
telephony/java/com/android/internal/telephony/cdma/RuimFileHandler.java
telephony/java/com/android/internal/telephony/cdma/RuimPhoneBookInterfaceManager.java
telephony/java/com/android/internal/telephony/cdma/SmsMessage.java
telephony/java/com/android/internal/telephony/cdma/TtyIntent.java
telephony/java/com/android/internal/telephony/cdma/package.html
telephony/java/com/android/internal/telephony/cdma/sms/BearerData.java
telephony/java/com/android/internal/telephony/cdma/sms/CdmaSmsAddress.java
telephony/java/com/android/internal/telephony/cdma/sms/SmsDataCoding.java
telephony/java/com/android/internal/telephony/cdma/sms/SmsEnvelope.java
telephony/java/com/android/internal/telephony/cdma/sms/UserData.java
telephony/java/com/android/internal/telephony/cdma/sms/package.html
telephony/java/com/android/internal/telephony/gsm/GsmDataConnectionTracker.java
telephony/java/com/android/internal/telephony/gsm/GsmSMSDispatcher.java
telephony/java/com/android/internal/telephony/gsm/GsmSmsAddress.java
telephony/java/com/android/internal/telephony/gsm/MccTable.java
telephony/java/com/android/internal/telephony/gsm/PdpConnection.java
telephony/java/com/android/internal/telephony/gsm/SIMFileHandler.java 
telephony/java/com/android/internal/telephony/gsm/SimPhoneBookInterfaceManager.java
telephony/jni/cdmasms/Android.mk
telephony/jni/cdmasms/cdma_sms_jni.cpp
telephony/jni/cdmasms/cdma_sms_jni.h
